version: '3'
services:
  openwebui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://172.16.239.11:11434
    restart: always
    networks:
      ollamanet:
        ipv4_address: 172.16.239.10
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
    networks:
      ollamanet:
        ipv4_address: 172.16.239.11

volumes:
  open-webui:
  ollama:

networks:
  ollamanet:
    name: ollama-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
